version: '3.4'

services:
  backend:
    container_name: intranetBack
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: intranet:latest
    ports:
      - 9000:9000
    restart: always
