version: '3.4'

services:
  intranetback:
    container_name: intranetback
    build:
      context: ./
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: intranetback:latest
    volumes:
      - /home/alverad/anexos:/anexos
    ports:
      - 9000:9000
    restart: always
