logging:
  level: 
    '[org.hibernate.stat]': debug

spring:
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL}
    username: intranet_admin
    password: intra2022admin
    driver-class-name: org.postgresql.Driver
    
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.format_sql]' : true
      '[hibernate.generate_statistics]' : true
      '[persistence.schema-generation.scripts.create-target]' : create.sql